'use strict';

var app = angular.module('app');

app.constant('AppConst', {
  viableMargin: 10,
  maxLoopCount: 1000000,
  resistanceDeduction: 1,
  blackList: [
    'Dragon Helm',
    'Iridescent Necklace',
    'Dragon Amulet',
    'Dragon Epaulettes',
    'Coat of Chain Scales',
    'Prismatic Ring',
    'Dragon Seal',
    'Dragon Shin Guards',
    'Dragon Slicer',
    'Prismatic Bow',
    'Mage Cape',
    'Prismatic Buckle',
    'Dragon Armor',
    'Dragon Coat'
  ],
  equipmentTypes: [
    'Helmet',
    'Cloak',
    'Amulet',
    'Epaulettes',
    'Breastplate',
    'Belt',
    'Ring',
    'Boots',
    'One-Handed Weapons',
    'Two-Handed Weapons',
    'Second Hand'
  ],
  statValues: {
    'Health Points': 0.3,
    'AP': 280,
    'MP': 180,
    'WP': 0,
    'Range': 120,
    'Control': 0,
    'Block': 4,
    'Critical Hit': 13,
    'Critical Mastery': 0.8,
    'Rear Mastery': 0,
    'Healing Mastery': 0,
    'Area Mastery': 0.8,
    'Single Target Mastery': 0,
    'Melee Mastery': 0,
    'Distance Mastery': 1,
    'Berserk Mastery': 0,
    'Mastery to 3 random elements': 1,
    'Mastery to 2 random elements': 0.8,
    'Mastery Fire': 0.25,
    'Mastery Earth': 0.25,
    'Mastery Air': 0.25,
    'Mastery Water': 0.25,
    'Elemental Resistance': 4,
    'Resistance to 3 random elements': 3,
    'Resistance to 2 random elements': 2,
    'Resistance to 1 random elements': 1,
    'Resistance Fire': 1,
    'Resistance Water': 1,
    'Resistance Air': 1,
    'Resistance Earth': 1,
    'Critical Resistance': 0,
    'Rear Resistance': 0,
    'Dodge': 0,
    'Lock': 0,
    'Initiative': 0,
    'Wisdom': 0,
    'Prospecting': 10
  },
  statLabels: [
    'Health Points',
    'AP',
    'MP',
    'WP',
    'Range',
    'Control',
    'Block',
    'Critical Hit',
    'Critical Mastery',
    'Rear Mastery',
    'Healing Mastery',
    'Area Mastery',
    'Single Target Mastery',
    'Melee Mastery',
    'Distance Mastery',
    'Berserk Mastery',
    'Mastery to 3 random elements',
    'Mastery to 2 random elements',
    'Mastery Fire',
    'Mastery Earth',
    'Mastery Air',
    'Mastery Water',
    'Elemental Resistance',
    'Resistance to 3 random elements',
    'Resistance to 2 random elements',
    'Resistance to 1 random elements',
    'Resistance Fire',
    'Resistance Earth',
    'Resistance Air',
    'Resistance Water',
    'Critical Resistance',
    'Rear Resistance',
    'Dodge',
    'Lock',
    'Initiative',
    'Wisdom',
    'Prospecting'
  ]
});
